name: Odoo package build and release

on:
  push:
    branches:
      - feature-*

env:
  REGISTRY_HOST: ${{ gitea.registry_host }}
  REGISTRY_USERNAME: ${{ gitea.repository_owner }}
  REGISTRY_PASSWORD: ${{ secrets.PAT }}

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prep
        run: apt intall -y dh-python
      - name: Build
        run: ./debian/rules binary
      - name: examine
        run: ls -l ..
      - name: Odoo Release
        id: release-action
        uses: https://gitea.com/actions/release-action@main
        with:
          files: |-
            ../*.deb
          api_key: '${{secrets.PAT}}'
